### ISSUE TITLE
http://dnd5eapi.co/api/classes/[class]/levels is returning an empty list.

### ISSUE THREAD

**Issue by clonex10100** [bagelbits/5e-srd-api#11]
It should return the leveling changes for the class, but instead I just get an empty list

**Comment by bagelbits** [comment]
I think this would get fixed as a result of [this PR.](https://github.com/bagelbits/5e-database/pull/130) The issue right now is right now it is looking for a URL with the index, and it's currently stored as the class name.

**Comment by bagelbits** [comment]
Also with [this PR.](#26)

**Comment by bagelbits** [comment]
This should be fixed with #26
