### ISSUE TITLE
Enhancement: Make query parameters case insensitive

### ISSUE THREAD

**Issue by geekychristine** [bagelbits/5e-srd-api#13]
When querying for entries, it should not matter if the consumer is requesting `/spells?name=Acid+Arrow` or `/spells?name=acid+arrow`, it should still match the intended resource(s).

**Comment by bagelbits** [comment]
You can probably use something similar to this to do it:
https://stackoverflow.com/questions/7101703/how-do-i-make-case-insensitive-queries-on-mongodb

Since the data will never have more then a couple hundred rows in any one table, the efficiency isn't nearly as important.

**Comment by bagelbits** [comment]
@geekychristine Sorry it's taken so long, but I'll be landing this change later today.
