### ISSUE TITLE
Choose either `async`/`await` or `.then` for resolving Promises, not both.

### ISSUE THREAD

**Issue by fergcb** [bagelbits/5e-srd-api#131]
Controllers currently use an unnecessary and confusing combination of `async`/`await` and `.then` to handle the Promise returned by Mongoose's `.find` and `.findOne`, such as in the following:

```
exports.showSpellcastingForClass = async (req, res, next) => {
  let urlString = '/api/classes/' + req.params.index;

  await Spellcasting.findOne({ 'class.url': urlString })
    .then(data => {
      res.status(200).json(data);
    })
    .catch(err => {
      next(err);
    });
};
```

This PR proposes changing all instances of this pattern, dropping either the `async`/`await` as follows:

```
exports.showSpellcastingForClass = (req, res, next) => {
  let urlString = '/api/classes/' + req.params.index;

  Spellcasting.findOne({ 'class.url': urlString })
    .then(data => {
      res.status(200).json(data);
    })
    .catch(err => {
      next(err);
    });
};
```
Or fully embracing `async`/`await` syntax  like so:
```
exports.showSpellcastingForClass = async (req, res, next) => {
  let urlString = '/api/classes/' + req.params.index;

  const data = await Spellcasting.findOne({ 'class.url': urlString }).catch(next);
  res.status(200).json(data);
};
```

**Comment by bagelbits** [comment]
Honestly, I'm fine with either way. `async/await` syntax seems slightly cleaner?

**Comment by fergcb** [comment]
Works for me. I'll get on this either this evening or tomorrow.

**Comment by ecshreve** [comment]
> Honestly, I'm fine with either way. `async/await` syntax seems slightly cleaner?

I agree here, I think using an `async/await` pattern lets us be explicit with how the promise is handled. Not _too_ big a deal because there aren't multiple promises getting handled in the same function, but `async/await` feels much more readable to me.

**Comment by bagelbits** [comment]
Well. I have a two PRs. One for each approach.
