### ISSUE TITLE
API data inconsistent with Database

### ISSUE THREAD

**Issue by cjo1pal** [bagelbits/5e-srd-api#17]
In looking through some of the recently closed issues, the database files have been updated, but when accessing the jsons through the urls, the changes are not reflected.
#32 still missing Legendary Actions from http://www.dnd5eapi.co/api/monsters/24
#48 is still incorrect in all equipment.
#11 is still missing Charisma score. http://www.dnd5eapi.co/api/monsters/1

**Comment by bagelbits** [comment]
These should all be fixed now in the API. The API should now start reflecting the Database changes.
