### ISSUE TITLE
Error searching for Equipment Packs

### ISSUE THREAD

**Issue by cjo1pal** [bagelbits/5e-srd-api#18]
I might just need to php code help, but I have a website that uses this API for the data. When searching through the equipment, my results always return invalid when I search for any equipment packs, ie Explorer's pack (equipment/155 - 160).
I also can only however search for items like Alchemist's supplies (equipment/161-177) if I copy and paste it directly from the overall list.
The apostrophe doesn't match what the keyboard inputs.
{"name":"Scholar's Pack","url":"http://www.dnd5eapi.co/api/equipment/160"},{"name":"Alchemist’s supplies","url":"http://www.dnd5eapi.co/api/equipment/161"}

feel free to try on [dnd.colinjoneill.com](dnd.colinjoneill.com)

**Comment by bagelbits** [comment]
I think it might be a PHP issue? That is odd though. Also the indices will be different now that we have the  most updated version of the DB running.

**Comment by bagelbits** [comment]
I'm closing this for now. Feel free to open this again if you're still having issues.
