### ISSUE TITLE
Create routes for the races

### ISSUE THREAD

**Issue by adrpadua** [bagelbits/5e-srd-api#2]
# Routes to add:

* http://dnd5eapi.co/api/races/dwarf
* http://dnd5eapi.co/api/races/elf
* http://dnd5eapi.co/api/races/halfling
* http://dnd5eapi.co/api/races/human
* http://dnd5eapi.co/api/races/dragonborn
* http://dnd5eapi.co/api/races/gnome
* http://dnd5eapi.co/api/races/half-elf
* http://dnd5eapi.co/api/races/half-orc
* http://dnd5eapi.co/api/races/tiefling

**Comment by bagelbits** [comment]
Well. These all exist.
