### ISSUE TITLE
Class returns wrong starting equipment url

### ISSUE THREAD

**Issue by vabrell** [bagelbits/5e-srd-api#53]
When fetching a class, the starting equipment section returns “/api/startingequipment/{number}”.
But the api route points towards “/api/starting-equipment/{number}”

**Comment by bagelbits** [comment]
Ah! That looks like an issue with https://github.com/bagelbits/5e-database

**Comment by bagelbits** [comment]
I'll throw up a quick PR and link it here!

**Comment by bagelbits** [comment]
https://github.com/bagelbits/5e-database/pull/146

**Comment by bagelbits** [comment]
This should be fixed now!
