### ISSUE TITLE
Documentation needs love

### ISSUE THREAD

**Issue by bagelbits** [bagelbits/5e-srd-api#57]
This should be done based on the sample data that's in there.

**Comment by elliotcubit** [comment]
Note: Some of the documentation is inconsistent with the behavior of the API. For example, the `ability_bonuses` subfield of `api/races` is type `[]int` in the documentation, but is something resembling `NamedAPIResource`.

This issue should include fixing the existing documentation reference tables, and verifying the examples match the current response formats. -- Copying the examples may lead to more documentation errors.
