### ISSUE TITLE
Https?

### ISSUE THREAD

**Issue by justingolden21** [bagelbits/5e-srd-api#6]
Would it be possible to update the api from http to https? Otherwise, ever website accessing the data cannot be https.

Thank you for listening and love your api.

**Comment by Jakobud** [comment]
It's free and easy guys: https://letsencrypt.org/

**Comment by bagelbits** [comment]
Website should now support HTTPS

**Comment by bagelbits** [comment]
I forgot to add a redirect so HTTP traffic will redirect to HTTPS
