### ISSUE TITLE
CR search filter for monsters

### ISSUE THREAD

**Issue by bagelbits** [bagelbits/5e-srd-api#64]
Something like `?challenge_rating=3`? Might be a little hairy for fractional CRs.

**Comment by DFreds** [comment]
Fractional CRs could just be .125, .25, .5... not ideal but an idea.

**Comment by bagelbits** [comment]
This is technically done but we're missing documentation for it.

**Comment by MasterEvarior** [comment]
> This is technically done but we're missing documentation for it.

I took the liberty of trying to add documentation for this, please tell me if this is so okey or if anything should be changed :)
![image](https://user-images.githubusercontent.com/36074738/92303388-a31c3100-ef74-11ea-9e10-5181198c804f.png)

**Comment by bagelbits** [comment]
You're awesome!

**Comment by MasterEvarior** [comment]
Sorry to open this issue again but I just saw that I made a spelling mistake in my pull request 😅.
It should not be ``monster?challenge_rating=2`` but ``monsters?challenge_rating=2``.
