### ISSUE TITLE
Single spellcasting path error

### ISSUE THREAD

**Issue by Marvko94** [bagelbits/5e-srd-api#70]
A single spellcasting api path like **"spellcasting/bard"** generates following error when clicking submit:
![spellcasting error 1](https://user-images.githubusercontent.com/61320936/84929944-d9ae8200-b0d0-11ea-85da-2974787f1c73.JPG)
![spellcasting error 2](https://user-images.githubusercontent.com/61320936/84929951-db784580-b0d0-11ea-8e0e-42f19615f0a2.JPG)

**Comment by bagelbits** [comment]
I'm so sorry that I just saw this. And also missed your PR. I'm actually going to close your PR in favor of this one: https://github.com/bagelbits/5e-srd-api/pull/74
