### ISSUE TITLE
CORS settings for client side apps

### ISSUE THREAD

**Issue by krisimmig** [bagelbits/5e-srd-api#9]
I was trying to get some data in a vuejs app, using axios for the api calls and it seems that the **http://www.dnd5eapi.co/api** has no CORS settings? So browser based requests are not allowed at the moment.

Can you allow requests to the API level for browsers as well?

**Comment by HectorHumanes** [comment]
I ask you to do that as well

**Comment by alfredosalzillo** [comment]
@krisimmig use this URL **[https://runkit.com/alfredosalzillo/dnd5eapi/2.0.0/api](https://runkit.com/alfredosalzillo/dnd5eapi/2.0.0/api)** instead of [http://www.dnd5eapi.co/api](http://www.dnd5eapi.co/api )

**Comment by bagelbits** [comment]
I assume this fixes that issue?
