### ISSUE TITLE
More search filter for monster

### ISSUE THREAD

**Issue by MasterEvarior** [bagelbits/5e-srd-api#95]
Some more possibilities to filter the monsters in a ``GET``-request would be great.
My ideas are the following:

- [ ] Alignment -> ``monsters?alignment=chaotic_evil``
- [ ] Types -> ``monsters?type=goblin`` 
- [ ] Resistances -> ``monsters?resistance=acid``
- [ ] Vulnerability -> ``monsters?vulnerability=acid``
- [ ] Immunities -> ``monsters?immunity=acid``

It would be great of course if they all supported multiple values, just like the ``challenge_rating`` filter.

**Comment by bagelbits** [comment]
I'd posit that Alignment would be this:
`monsters?alignment=chaotic,evil`
This allows you to search for just chaotic or just evil monsters as well.

**Comment by djaustin** [comment]
To add to this issue, a filter for environment would be very handy for some projects I've been working on too.

**Comment by bagelbits** [comment]
It's a good idea but not feasible since it comes from the DMG. :(

**Comment by MasterEvarior** [comment]
> I'd posit that Alignment would be this:
> `monsters?alignment=chaotic,evil`
> This allows you to search for just chaotic or just evil monsters as well.  

Would that mean if I search for `monsters?alignment=chaotic,evil` it returns monsters that are chaotic **and** evil or chaotic **or** evil?

**Comment by bagelbits** [comment]
`monsters?alignment=chaotic,evil` would give you chaotic or evil. But I believe you should be able to do `monsters?alignment=chaotic evil`, which would give you chaotic evil. Because really at this point, you'd just build a regex to run against a particular field.

**Comment by djaustin** [comment]
I would be keen to start working on this if no one has yet.

**Comment by bagelbits** [comment]
@djaustin Take it away!

**Comment by djaustin** [comment]
Some questions so far when considering implementation:
* Should all filters accept multiple values? e.g. `monsters?resistance=acid,cold`
* Should filters use partial matching or exact matching? e.g. monsters?resistance=ac,co`

**Comment by bagelbits** [comment]
> * Should all filters accept multiple values? e.g. `monsters?resistance=acid,cold`

Yes. I can't see any reason why it shouldn't.

> * Should filters use partial matching or exact matching? e.g. `monsters?resistance=ac,co`

Yes. Especially since resistances, vulnerabilities, and immunities get weird fast for some monsters.

**Comment by bagelbits** [comment]
So..... now that we support GraphQL, is this still as necessary?

**Comment by MasterEvarior** [comment]
For me GraphQL would suffice. Not sure though if @djaustin wants merge his progress before we close this issue or not.

**Comment by bagelbits** [comment]
I'll leave it open for another week and then I'll close everything out if I don't hear anything.
