### ISSUE TITLE
Spellcasting appears twice in docs, one instance is outdated

### ISSUE THREAD

**Issue by fergcb** [bagelbits/5e-srd-api#99]
Examples of the spellcasting document response occur twice in the API docs. Once under the "Class" heading, for the `api/classes/{index}/spellcasting` endpoint, and once for the `api/spellcasting/{index}` endpoint.

The two could perhaps be merged, listing both URLs, but with the same example result, as the response for both is identical. Simple solution, should make things easier in the long run.

Alternatively, the outdated example could simply be updated. Easier for now, but more hassle in the future.

**Comment by bagelbits** [comment]
I think combining them makes the most sense, since they do the same thing.
